version: '3.8'

services:
  database:
    container_name: container-dealchat-backend
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dealchat-db

  rabbitmq:
    image: rabbitmq:management
    container_name: container-dealchat-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

  app:
    build: .
    container_name: container-dealchat-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/dealchat-db
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASS=mypassword
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - database
      - rabbitmq
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
